package personal.ciai.vetclinic

import java.util.Date
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.assertAll
import personal.ciai.vetclinic.model.Appointment
import personal.ciai.vetclinic.model.Pet

object TestUtils {
    val dogExample = Pet(
        0,
        "Bulldog",
        4,
        notes = "Happy dog",
        physicalDescription = "Big Dog",
        medicalRecord = "Medical stuff",
        photo = null
    )
    val pigExample = Pet(
        0,
        "Pig",
        1,
        notes = "Cute",
        physicalDescription = "Fluffy",
        medicalRecord = "Medical stuff",
        photo = null
    )
    val iguanaExample = Pet(
        0,
        "Iguana",
        2,
        notes = "Looks angry",
        physicalDescription = "Green",
        medicalRecord = "Medical stuff",
        photo = null
    )
    val petList = listOf<Pet>(dogExample, pigExample, iguanaExample)

    val appointmentExample1 = Appointment(0, Date(1571414431763), dogExample, "Scheduled for health stuff")

    val appointmentList = listOf<Appointment>(appointmentExample1)

    fun assertPetEquals(p1: Pet, p2: Pet) {
        assertAll("Is pet the same?",
//            { assertNotEquals(p1.id, p2.id) }, //ID changes because its auto-generated
            { assertEquals(p1.species, p2.species) },
            { assertEquals(p1.age, p2.age) },
            { assertEquals(p1.notes, p2.notes) },
            { assertEquals(p1.physicalDescription, p2.physicalDescription) },
            { assertEquals(p1.medicalRecord, p2.medicalRecord) },
            { assertEquals(p1.appointments, p2.appointments) }
        )
    }

    fun assertAppointmentEquals(a1: Appointment, a2: Appointment) {
        assertAll("Is appointment the same?",
//            { assertNotEquals(a1.id, a2.id) }, // the id is different because it is generated by Spring
            { assertEquals(a1.date, a2.date) },
            { assertEquals(a1.description, a2.description) },
            { assertPetEquals(a1.pet, a2.pet) }
        )
    }
}
