package personal.ciai.vetclinic.UnitTests.repositoryTests

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertAll
import org.junit.jupiter.api.extension.ExtendWith
import org.mockito.Mockito
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.junit.jupiter.SpringExtension
import org.springframework.transaction.annotation.Transactional
import personal.ciai.vetclinic.ExampleObjects.exampleObjects.admin1
import personal.ciai.vetclinic.ExampleObjects.exampleObjects.admin3
import personal.ciai.vetclinic.model.Pet
import personal.ciai.vetclinic.repository.AdministrativeRepository

@ExtendWith(SpringExtension::class)
@SpringBootTest
@Transactional
class AdministrativeRepositoryTests {
    @Autowired
    lateinit var admin: AdministrativeRepository

    @Test
    fun `basic test on findAll`() {
        assertEquals(admin.findAll().toList(), emptyList<Pet>())
    }

    @Test
    fun `basic test on save and delete`() {
        val admin01 = admin.save(admin1)
        assertNotEquals(admin1.id, admin01.id) // the id is different because it is generated by Spring
        assertEquals(admin1.username, admin01.username)

        val saved = admin.findById(admin01.id).get()

        assertAll("Is admin the same",
            { assertNotEquals(admin1.id, saved.id) },
            { assertEquals(admin1.name, saved.name) },
            { assertEquals(admin1.username, saved.username) }
        )

        admin.delete(admin01)

        assertTrue(admin.findAll().toList().size == 0)
    }

    fun <T> nonNullAny(t: Class<T>): T = Mockito.any(t)

    @Test
    fun `another test on save and delete`() {

        val admin01 = admin.save(admin1)
        assertNotEquals(admin01.id, admin1.id) // the id is different because it is generated by Spring
        assertEquals(admin01.username, admin1.username)
        assertEquals(admin01.email, admin1.email)

        assertEquals(admin.findAll().toList(), listOf(admin01))

        val admin03 = admin.save(admin3)
        assertNotEquals(admin03.id, admin3.id) // the id is different because it is generated by Spring
        assertEquals(admin03.email, admin3.email)
        assertEquals(admin03.username, admin3.username)

        assertEquals(admin.findAll().toList(), listOf(admin01, admin03))

        admin.delete(admin01)

        assertTrue(admin.findAll().toList().size == 1)

        admin.delete(admin03)

        assertTrue(admin.findAll().toList().size == 0)
    }
}
